config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :posts do
    collection do
      get :lost
      get :found
    end
  end
  resources :pets do
    resources :posts
  end

  resources :posts do
    resources :chatrooms, only: [:create, :destroy]
  end

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end

  get 'pet_breeds', to: "pets#get_breeds", as: :get_breeds
  get '/myposts', to: "posts#myposts", as: :my_posts
  get 'posts/locate', to: "posts#locate", as: :locate
  # get 'post/:id/edit', to: "posts#edit", as: :post_edit
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
require "json"
require "rest-client"

class Pet < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  validates :size, :gender, :color, :breed, :animal, presence: true
  has_many_attached :photos

  SIZE = [
    ['Todos',nil],
    ['Otros','otros'],
    ['Toy','toy'],
    ['Pequeño','pequeño'],
    ['Mediano','mediano'],
    ['Grande','grande'],
  ]

  COLOR = [
    ['Todos',nil],
    ['Otros','otros'],
    ['Abigarrado','abigarrado'],
    ['Albinos','albinos'],
    ['Arlequín','arlequín'],
    ['Atigrados ','atigrados'],
    ['Beige','beige'],
    ['Blanco','blanco'],
    ['Café','café'],
    ['Chocolate','Chocolate'],
    ['Multi color','multi color'],
    ['Monocromáticos','Monocromáticos'],
    ['Negro','negro'],
  ]

  GENDER = [
    ['Todos',nil],
    ['Otros','otros'],
    ['Hembra','hembra'],
    ['Macho','macho']
  ]

  ANIMAL = [
    ['Todos',nil],
    ['Otros','otros'],
    ['Perro','perro'],
    ['Gato','gato']
  ]

  def self.breeds
    breeds_response = RestClient.get("https://dog.ceo/api/breeds/list/all")
    breeds_hash = JSON.parse(breeds_response)['message']
    breeds = breeds_hash.keys
    breeds_option = breeds.map do |breed|
      [breed.capitalize, breed]
    end
    return [
      ['Todos',nil],
      ['Mestizo','mestizo'],
      ['Otros','otros'],
    ].concat breeds_option
  end

  def self.other_breeds
    [
      ['Todos',nil],
      ['Mestizo','mestizo'],
    ]
  end

  def self.breed_cats
    breeds_response = RestClient.get("https://api.thecatapi.com/v1/breeds")
    breeds = JSON.parse(breeds_response)
    breeds_option = breeds.map do |breed_hash|
      breed = breed_hash['name']
      [breed.capitalize, breed]
    end
    return [
      ['Todos',nil],
      ['Mestizo','mestizo'],
      ['Otros','otros'],
    ].concat breeds_option
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
    if params[:breed].present?
      @pets = Pet.where(breed: params[:breed])
    end
    if params[:size].present?
      puts "here2"
      @pets = Pet.where(size: params[:size])
    end
    if params[:color].present?
      puts "here2"
      @pets = Pet.where(color: params[:color])
    end
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to new_pet_post_path(@pet)
    else
      render "new"
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      flash['success'] = 'Se actualizó con éxito'
      redirect_to my_posts_path
    else
      redirect_to edit_post_path(@post)
    end
  end

  def get_breeds
    if params[:pet_animal] == 'perro'
      render json: Pet.breeds
    elsif params[:pet_animal] == 'otros'
      render json: Pet.other_breeds
    else
      render json: Pet.breed_cats
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :gender, :age, :size, :color, :breed, :animal, photos: [])
  end
end

app/views/pets/_filters.html.erb

<h4>Filtrar por:</h4>
<%= form_with url: pets_path, method: :get, local: true do |f| %>
<div class="d-flex align-items-center justify-content-around cont-filters">
    <div class="form-group col-3">
<%= f.label :breed, "Breed" %>
<%= f.select :breed,
 options_for_select(Pet.breeds),
        {},
        { class:"form-control" }
        %>

</div>
<div class="form-group col-3">
  <%= f.label :size, "Size" %>
  <%= f.select :size,
   options_for_select( Pet::SIZE
        ),
        {},
        { class:"form-control" }
        %>
</div>
<div class="form-group col-3">
  <%= f.label :color, "Color" %>
  <%= f.select :color,
  options_for_select(Pet::COLOR
        ),
        {},
        { class:"form-control" }
        %>
</div>

<%= f.select :breed,
  options_for_select(Pet::ANIMAL),
        {},
        { class:"form-control" }
        %>
</div>

<%= f.submit "Filtrar", class: "btn-light-gradient " %>

</div>
<% end %>

app/views/pets/_form.html.erb
<input type="hidden" id="get_breeds_path" value="<%= get_breeds_path %>">
<%= simple_form_for @pet do |f|%>
  <div class="row">
    <div class="col align-items-center">
    <%= f.input :name, placeholder: "Nombre", label: false %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= f.input :animal, collection: Pet::ANIMAL.reject { |s| s[0]== "Todos" }, include_blank: false, :prompt => 'animal',  label: false %>
    </div>
    <div class="col">
      <%= f.input :gender, collection: Pet::GENDER.reject { |s| s[0]== "Todos" }, include_blank: false, :prompt => 'Sexo', label: false %>
    </div>
  </div>
  <div class="row">
    <div class="col">
        <%= f.input :size, collection: Pet::SIZE.reject { |s| s[0]== "Todos" }, include_blank: false, :prompt => 'Tamaño',  label: false %>
    </div>
    <div class="col">
      <%= f.input :age, placeholder: "Edad", label: false, collection: 0..18, include_blank: false, :prompt => 'Edad',  label: false %>
    </div>
  </div>
  <div class="row">
    <div class="col">
        <%= f.input :breed, collection: Pet.breeds.reject { |s| s[0]== "Todos" }, include_blank: false, :prompt => 'Raza',  label: false %>
    </div>
    <div class="col">
        <%= f.input :color, collection: Pet::COLOR.reject { |s| s[0]== "Todos" }, include_blank: false, :prompt => 'Color',  label: false %>
        <!--<%= f.input :animal, placeholder: "Tipo de Animal", label: false %>-->
    </div>
    <!--<div class="col">
        <%= f.input :animal, collection: Pet::ANIMAL.reject { |s| s[0]== "Todos" }, include_blank: false, :prompt => 'animal',  label: false %>
        <%= f.input :animal, placeholder: "Tipo de Animal", label: false %>
    </div>-->
  </div>
  <div class="row">
    <div class="col">
      <%= f.input :photos, as: :file, label: "Suba una foto", label_html: { class: "btn-gradient" }, input_html: { multiple: true, class: "d-none" } %>
    </div>
  </div>
  <div class="container text-center">
    <div class="row">
      <div class="col">
        <%= f.button :submit, "Continuar", class: "btn-gradient" %>
      </div>
    </div>
  </div>
  <% end %>

app/views/pets/edit.html.erb
<div class="container mt-5">
  <h2 class="mb-3">Editar Mascota</h2>
  <%= render "form", pet: @pet%>
</div>

app/views/pets/index.html.erb
<div class="container">
<div class="row">
  <div class="col pt-4">
    <%= render "filters", pets: @pets %>
    <div class="cards col-pets">
      <% @pets.each do |pet| %>
        <%= link_to  post_path(pet), class: "card-trip-wrapper" do %>
        <div class="card-trip">
          <% if !pet.photos.empty?  %>
            <%= cl_image_tag pet.photos.first.key, height: 150, width: 200, crop: :fill %>
          <% end %>
          <div class="card-trip-infos">
            <div >
              <h4><%= pet.name %></h4>
              <p class="t-overflow"><%= pet.breed %></p>
            </div>
          </div>
        </div>
      
  <% end %>

      <% end %>
    </div>
  </div>
 <div class="col-6 d-none">
        <div data-controller="map-index">
        <div id="map" data-map-index-etarget="map"
          style="width: 100%; height: 800px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
</div>

</div>

app/views/pets/new.html.erb
<div class="container mt-5">
  <h2 class="mb-3">Nueva Mascota</h2>
  <%= render "form", pet: @pet%>
</div>