config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :posts do
    collection do
      get :lost
      get :found
    end
  end
  resources :pets do
    resources :posts
  end

  resources :posts do
    resources :chatrooms, only: [:create, :destroy]
  end

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end

  get 'pet_breeds', to: "pets#get_breeds", as: :get_breeds
  get '/myposts', to: "posts#myposts", as: :my_posts
  get 'posts/locate', to: "posts#locate", as: :locate
  # get 'post/:id/edit', to: "posts#edit", as: :post_edit
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_avatar.html.erb
<% if user[:avatar].attached? %>
  <%= cl_image_tag user[:avatar].key, class: "avatar dropdown-toggle"%>
<% else %>
  <%= image_tag "user.png", alt: "User", class: "avatar dropdown-toggle"%>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash[:success] %>
  <script>
    Swal.fire({
      text: "<%= flash[:success] %>",
      icon: 'success',
      confirmButtonText: 'OK'
    })
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-3 mt-4 footer">
  <div class="footer-section" >
    <p class="text-center text-muted"><strong>WeFindPets</strong></p>
    <p class="text-center text-muted">Juntos, correremos la voz y ayudaremos a más mascotas perdidas a encontrar el camino a casa.</p>
  </div>
  <br>
  <div class="border-bottom">
    <ul class="nav justify-content-around footer-legal">
      <li class="nav-item"><strong><%= link_to "Perdidos", lost_posts_path, class: "nav-link px-2 text-muted" %></strong></li>
      <li class="nav-item"><strong><%= link_to "Encontrados", found_posts_path, class: "nav-link px-2 text-muted" %></strong></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"><strong>Contacto</strong></a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"><strong>FAQ</strong></a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"><strong>Legal</strong></a></li>
    </ul>
    </div>
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <div class="footer-links">
      <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
      <a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a>
      <a href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
    </div>
  </ul>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon " id="navbar">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "We_Find_Petscrop.png", class: "logo", alt: "WeFindPets"%>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Inicio", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">

          <%= link_to "Mensajes", chatrooms_path, class: "nav-link" %>

        </li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "user.png", alt: "User", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Editar perfil", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Crea una mascota", new_pet_path, class: "dropdown-item" %>
            <%= link_to "Mis publicaciones", my_posts_path(), class: "dropdown-item" %>
            <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Inicia Sesión", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>