config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :posts do
    collection do
      get :lost
      get :found
    end
  end
  resources :pets do
    resources :posts
  end

  resources :posts do
    resources :chatrooms, only: [:create, :destroy]
  end

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end

  get 'pet_breeds', to: "pets#get_breeds", as: :get_breeds
  get '/myposts', to: "posts#myposts", as: :my_posts
  get 'posts/locate', to: "posts#locate", as: :locate
  # get 'post/:id/edit', to: "posts#edit", as: :post_edit
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="banner">
  <div class="container text-left banner-title d-flex justify-content-center align-items-center">
    <%= image_tag "snap.png", width: 550, class: "img-banner-1",alt: "number"%>
    <div class="banner-title text-center pt-5">
      <h1>We Find Pets</h1>
      <p>¿Perdiste a tu mascota?</p>
      <p>Te ayudamos a encontrarla.</p>
      <div class="container pt-3 d-flex justify-content-center btn-banner">
        <%= link_to "Publicar", new_pet_path, class: "btn btn-gradient-banner mr-5" %>
        <%= link_to "Buscar", posts_path, class: "btn btn-gradient-banner " %>
      </div>
    </div>
    <%= image_tag "walking.png", width: 580, class: "img-banner-2", alt: "number"%>
  </div>
</div>
<!--Pasos a seguir-->
<section class="py-5">
  <div class="container text-center img-size" >
      <div class="row">
        <div class="col">
          <h1 class="py-5 text-title">Empieza a usar We Find Pets fácilmente</h1>
          <br>
        </div>
      </div>
      <div class="row steps-wrapper">
        <div class="col" data-aos = "zoom-in">
          <%= image_tag "number-1-64px.png", width: 30, alt: "number"%>
          <br>
          <%= image_tag "forn-pet.png", width: 300, alt: "forn-pet"%>
          <h2 class="py-5 text-subtitle">Llena los datos de la mascota</h2>
          <p class="text-follow">Crea una cuenta y llena los datos con las características de la mascota</p>
        </div>
        <div class="col" data-aos = "zoom-in">
          <%= image_tag "number-2-64px.png", width: 30, alt: "number"%>
          <br>
          <%= image_tag "share-pets.png", width: 300, alt: "share-pets"%>
          <h2 class="py-5 text-subtitle"> Crea la publicación</h2>
          <p class="text-follow">Completa los datos del aviso con información de lugar y fecha del reporte</p>
        </div>
        <div class="col" data-aos = "zoom-in">
          <%= image_tag "number-3-64px.png", width: 30, alt: "number"%>
          <br>
          <%= image_tag "pet-reunion.png", width: 300, alt: "pet-reunion"%>
          <h2 class="py-5 text-subtitle">Encuentra a tu mascota</h2>
          <p class="text-follow">Una vez publicado el anuncio, si alguien ve a tu mascota te contactará fácilmente</p>
        </div>
      </div>
    </div>
</section>

<!--lista de mascotas perdidas y encontradas-->
<section>
  <div class="busqueda">
    <div class="row container m-auto">
      <div class="col">
        <!--<h2 class="mt-5 mb-5 mr-5">Mascotas Encontradas &gt;</h2>-->
          <div class="py-3">
          <%= link_to "Mascotas Encontradas >", found_posts_path, class:"subtitle text-decoration-none"%>
          </div>
          <div class="cards" data-aos = "flip-left">
            <% @last_founds.each do |pet| %>
              <%= link_to post_path(pet.posts.first), class:"decoration" do  %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= pet.photos.empty? ? "https://source.unsplash.com/800x600/?dog&lost" :  cl_image_path(pet.photos.first.key) %>')">
                  <%= pet.name%>
                </div>
              <% end %>
            <% end %>
            </div>
        <!--<h2 class="mt-5 mb-5 mr-5">Mascotas Perdidas &gt;</h2>-->
          <div class="py-3">
            <%= link_to "Mascotas Perdidas >", lost_posts_path, class:"subtitle text-decoration-none"%>
          </div>
          <div class="cards" data-aos = "flip-left">
            <% @last_losts.each do |pet| %>
              <%= link_to post_path(pet.posts.first), class:"decoration" do %>
                <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= pet.photos.empty? ? "https://source.unsplash.com/800x600/?dog&lost" :  cl_image_path(pet.photos.first.key) %>')">
                  <%= pet.name %>
                </div>
              <% end %>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</section>
<br>
<!--testimonios-->
<section class="testimonial-section">
  <h1 class="title-testimonial text-title">Testimonios</h1>
  <div class="d-flex justify-content-center testimonial-wrapper flex-wrap">
    <div class="py-5  testimonial-card">
      <div class="row align-items-center testimonial-column" style="height : 100%">
        <div class="col-6 d-flex justify-content-center ">
          <%= image_tag "adam-griffith-sWkkIiTJMYc-unsplash.jpg", height: 200, width: 200,class:"img-testimonial" , alt: "Reunited"%>
        </div>
        <div class="col-6 text-conten">
          <div class="align-self-baseline testimonial">
            <p>"Gracias a WeFindPets pude encontrar rápidamente a mi mascota"</p>
          </div>
          <div class="tex-testimonial">
            <p>Gracias a We Find Pets pude encontrar a mi mascota de forma rápida</p>
            <p>-Carolina U-</p>
          </div>
        </div>
      </div>
    </div>
    <div class="py-5 testimonial-card">
      <div class="row align-items-center testimonial-column"  style="height : 100%">
        <div class="col-6 d-flex justify-content-center ">
          <%= image_tag "dog-unsplash.jpg", height: 200, width: 200,class:"img-testimonial",  alt: "Reunited"%>
        </div>
        <div class="col-6 text-conten">
          <div class="align-self-baseline testimonial">
            <p>"Una foto ayudó a Loki a llegar a casa"</p>
          </div>
          <div class="tex-testimonial">
            <p>Después de estar perdido tres meses, We find pets reunió a un perro desaparecido con su familia.</p>
            <p>-Emmanuel T-</p>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
</section>