config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :posts do
    collection do
      get :lost
      get :found
    end
  end
  resources :pets do
    resources :posts
  end

  resources :posts do
    resources :chatrooms, only: [:create, :destroy]
  end

  resources :chatrooms, only: [:index, :show] do
    resources :messages, only: :create
  end

  get 'pet_breeds', to: "pets#get_breeds", as: :get_breeds
  get '/myposts', to: "posts#myposts", as: :my_posts
  get 'posts/locate', to: "posts#locate", as: :locate
  # get 'post/:id/edit', to: "posts#edit", as: :post_edit
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :pet
  validates :title, :description, :address, :status, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :chatrooms
  validates :description, length: { minimum: 10 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  helper_method :build_post_path
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      query = " \
        posts.address @@ :query \
        OR posts.title @@ :query \
        OR pets.breed @@ :query \
        OR pets.size @@ :query \
        OR pets.gender @@ :query \
        OR pets.color @@ :query \
        OR pets.animal @@ :query \
      "
      @posts = Post.joins(:pet).where(query, query: "%#{params[:query]}%").order("id ASC")
    elsif params[:breed].present?
      sql_query = "pets.breed ILIKE :query"
      @posts = Post.joins(:pet).where(sql_query, query: params[:breed])
    elsif params[:size].present?
      sql_query = "pets.size ILIKE :query"
      @posts = Post.joins(:pet).where(sql_query, query: params[:size])
    elsif params[:color].present?
      sql_query = "pets.color ILIKE :query"
      @posts = Post.joins(:pet).where(sql_query, query: params[:color])
    elsif params[:gender].present?
      sql_query = "pets.gender ILIKE :query"
      @posts = Post.joins(:pet).where(sql_query, query: params[:gender])
    elsif params[:animal].present?
      sql_query = "pets.animal ILIKE :query"
      puts "no lo borren por favor"
      @posts = Post.joins(:pet).where(sql_query, query: params[:animal])
    else
      @posts = Post.all.order("id ASC")
    end
    @markers = @posts.geocoded.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        info_window: render_to_string(partial: "info_window", locals: { post: post })
      }
    end
  end

  def show
    @post = Post.find(params[:id])
    @message = Message.new
    @message.user = current_user
    authorize @post
    @marker = { lat: @post.latitude, lng: @post.longitude }
  end

  def edit
    @post = Post.find(params[:id])
    @pet = @post.pet
    authorize @post
    @marker = { lat: @post.latitude, lng: @post.longitude }
  end

  def new
    @post = Post.new
    @pet = Pet.find(params[:pet_id])
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @pet = Pet.find(params[:pet_id])
    @post.pet = @pet
    @post.user = current_user
    authorize @post
    if @post.save
      flash['success'] = 'Se creó la publicación con éxito'
      redirect_to pet_post_path(@pet, @post)
    else
      render "new"
    end
  end

  def locate

  end

  def update
    @post = Post.find(params[:id])
    @pet = Pet.find(params[:pet_id])
    authorize @post
    if @post.update(post_params)
      flash[:success] = "Se actualizó correctamente"
      redirect_to  my_posts_path
    else
      flash[:alert] = "Ingrese datos correctos"
      # redirect_to post_edit_path(@post)
      redirect_to edit_post_path(@post)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    # authorize @flat
    @post.destroy
    flash[:success] = "Se elimino correctamente"
    redirect_to my_posts_path
  end


  #def build_post_path(post)
    #@is_my_post_path ?  post_edit_path(post) : post_path(post)
  #end



  def myposts
    user_id = current_user.id
    @posts = policy_scope(Post).where("user_id = #{user_id}")
    @markers = @posts.geocoded.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        info_window: render_to_string(partial: "info_window", locals: { post: post })
      }
    end
    # redirect_to posts_path
  end

  def lost
    @posts = Post.where("status ILIKE ?", "Perdido").order("id ASC")
    @markers = @posts.geocoded.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        info_window: render_to_string(partial: "info_window", locals: { post: post })
      }
    end
  end

  def found
    @posts = Post.where("status ILIKE ?", "Encontrado").order("id ASC")
    @markers = @posts.geocoded.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        info_window: render_to_string(partial: "info_window", locals: { post: post })
      }
    end
  end



  private

  def post_params
    params.require(:post).permit(:title, :description, :address, :status,  photos: [])
  end
end

app/views/posts/_contact_form.html.erb
<%#= simple_form_for [@post,@message] do |form| %>
  <div class="modal fade" id="contactForm">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Envia un mensaje</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-inputs">
            <div class="form-group">
              <%#= form.input :description, as: :text %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%#= form.button :submit, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<%# end %>

app/views/posts/_create_form.html.erb
<!--
<%= simple_form_for [@pet, @post] do |f| %>
      <div class="row">
        <div class="col-6">
          <%= f.input :title, placeholder: "Título", label: false %>
        </div>
      </div>
      <div class="row">
          <div class="col-6">
            <%= f.input :description, as: :text , placeholder: "Descripcion", label: false %>
          </div>
          <div class="col-6">
            <%= f.input :status, label: "Reportar como", as: :radio_buttons, collection: ['Perdido', 'Encontrado'] %>
          </div>
        </div>
      <div class="row">
        <div class="col-6">
          <%= f.input :address, placeholder: "Dirección", label: false %>
        </div>
        <div class="col-6 align-self-start">
          <%= link_to "Previsualizar", locate_path(@post), class: "btn btn-primary", id: "preview" %>
        </div>
      </div>
      <div class="container text-center">
        <div class="row">
          <div class="col">
            <%= f.button :submit, "Publicar", class: "btn btn-info" %>
          </div>
        </div>
      </div>
      <%end  %>
    </div>
    <p class="d-none">Coordenadas</p>
    <div class="col-6">
        <div id="map" style="height: 300px; width: 600px"></div>
    </div>
</div>-->

app/views/posts/_filters.html.erb
<input type="hidden" id="get_breeds_path" value="<%= get_breeds_path %>">
<%= form_with url: posts_path, method: :get, local: true do |f| %>
  <div class="d-flex align-items-center justify-content-around cont-filters pl-0">
  <div class="row">
      <div class="form-group col-md-auto">
        <%= f.label :breed, "Raza" %>
        <%= f.select :breed,
        options_for_select([["Todos", nil]]),
                {},
                { class:"form-control", id: "pet_breed"}
                %>
      </div>
      <div class="form-group col-md-auto">
        <%= f.label :size, "Tamaño" %>
          <%= f.select :size,
          options_for_select(Pet::SIZE
                ),
                {},
                { class:"form-control" }
                %>
      </div>
  </div>
  <div class="row">
      <div class="form-group col-md-auto">
        <%= f.label :color, "Color" %>
        <%= f.select :color,
        options_for_select(Pet::COLOR
                ),
                {},
                { class:"form-control"}
                %>
      </div>
      <div class="form-group col-md-auto">
        <%= f.label :gender, "Sexo" %>
        <%= f.select :gender,
        options_for_select(Pet::GENDER
                ),
                {},
                { class:"form-control" }
                %>
      </div>
      <div class="form-group col-md-auto">
        <%= f.label :animal, "Animal" %>
        <%= f.select :animal,
        options_for_select(Pet::ANIMAL
                ),
                {},
                { class:"form-control", id: "pet_animal" }
                %>
      </div>
  </div>
      <%= f.submit "Filtrar", class: "btn-light-gradient", id: 'filterbtn' %>
  </div>
<% end %>

app/views/posts/_index.html.erb
<div class="container my-5" data-controller="search-posts">

  <div>
  <div class="container">
    <div class="row pl-0">
      <div class="col-12 pb-3 pl-0">
        <h2>Busca tu mascota</h2>
      </div>
    </div>
  <div class="container pl-0" data-controller="show-filters">
    <div class="d-none" data-show-filters-target="filter">
      <div class="row">
          <div class="col-12"><%= render "filters" %></div>
      </div>
    </div>
   <div class="row">
    <div class="col-4 pl-0">
      <button class="btn-light-gradient" data-show-filters-target="button" data-action="click->show-filters#show">Búsqueda Avanzada</button>
    </div>
    <div class="col-8 pr-0">
      <%= simple_form_for :search, url: posts_path, method: :get, html: { data: { search_posts_target: 'form' } } do |f| %>
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="query" id="search_query" data-search-posts-target="input" />
          <button name="button" type="submit" class="btn btn-flat" data-search-posts-target="button">
            <i class="fas fa-search"></i> Buscar
          </button>
        </div>
      <% end %>
      </div>
    </div>
   </div>
  </div>
  </div>
  <p class="pb-3">Resultados de la búsqueda:
    <% if @posts.size > 1  || @posts.size == 0%>
      <%= pluralize @posts.size, "publicaciones" %>
    <% else %>
      <%=  pluralize @posts.size, "publicación" %>
    <% end %>
  </p>

  <div class="row">
    <div class="col-4">
      <div data-controller="map-index">
          <div class="map-container" id="map" data-map-index-target="map"
            style="width: 100%; height: 850px; position: sticky;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
      </div>
    </div>
    <div class="col-8 cards-scroll">
        <div class="cards" data-search-posts-target="posts">
          <% @posts.each do |post| %>
            <%= link_to  post_path(post), class: "card-trip-wrapper" do %>
              <div class="card-trip">
                  <% if !post.pet.photos.empty?  %>
                    <%= cl_image_tag post.pet.photos.first.key, height: 150, width: 200, crop: :fill %>
                  <% end %>
                  <div class="card-trip-infos">
                    <div>
                      <h5 class="t-overflow"><%= post.title %></h5>
                      <p class="t-overflow"><%= post.description %></p>
                    </div>
                  </div>
              </div>
            <% end %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/posts/_jumbotron.html.erb
<div class="jumbotron">
  <h3 class="display-8"><%= info[:title] %></h3>
  <p class="lead"></p>
  <hr class="my-4">
  <%= link_to "#{info[:btn]}", info[:btn_path], class: "btn-gradient" %>
</div>

app/views/posts/_photos_gallery.html.erb
<% @post.pet.photos.each_with_index do |photo,index| %>
  <div class="modal fade" id="<%= "photo#{index}" %>">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <div data-zoom="<%= cl_image_path(photo.key) %>">
            <%= cl_image_tag photo.key, height: 500, width: '100%' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb

<div class="container mt-5" data-controller="show-map">
  <div class="row">
    <div class="col-6">
      <div class="d-flex justify-content-center">
        <h3 class="mb-3">Editar publicación</h3>
      </div>
      <%= simple_form_for [@pet, @post] do |f| %>
      <div class="row">
        <div class="col-6">
          <%= f.input :title, placeholder: "Título", label: false %>
        </div>
      </div>
      <div class="row">
          <div class="col-6">
            <%= f.input :description, as: :text , placeholder: "Descripcion", label: false %>
          </div>
          <div class="col-6">
            <%= f.input :status, label: "Reportar como", as: :radio_buttons, collection: ['Perdido', 'Encontrado'] %>
          </div>
        </div>
      <div class="row">
        <div class="col-6">
          <%= f.input :address, placeholder: "Dirección", label: false %>
        </div>
        <div class="col-6 align-self-start">
          <%= link_to "Previsualizar", locate_path(@post), class: "btn btn-primary d-none", id: "preview" %>
        </div>
      </div>
      <div class="container text-center">
        <div class="row">
          <div class="col">
            <%= f.button :submit, "Guardar", class: "btn btn-gradient" %>

          </div>
        </div>
      </div>
      <%end  %>
    </div>
    <p class="d-none">Coordenadas</p>
    <div class="col-6">
        <div id="map" style="height: 300px; width: 600px" data-marker="<%= @marker.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" data-show-map-target="map"></div>
    </div>
  </div>
</div>

app/views/posts/found.html.erb
<%= render "index", posts: @posts, markers: @markers %>

app/views/posts/index.html.erb
<%= render "index", posts: @posts, markers: @markers %>

app/views/posts/locate.html.erb
<p>Coordenadas</p>
<div id="mapa">
</div>

app/views/posts/lost.html.erb
<%= render "index", posts: @posts, markers: @markers %>

app/views/posts/myposts.html.erb
<div class="container my-5" data-controller="search-posts">
  <% if @posts.size != 0 %>
    <h3 class="pb-3">Mis publicaciones</h3>
    <div class="row">
      <div class="col-4">
        <div data-controller="map-index">
          <div id="map" data-map-index-target="map"
            style="width: 100%; height: 800px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
      <div class="col-8">
          <div class="cards" data-search-posts-target="posts">
            <% @posts.each do |post| %>
                <div class="card-trip">
                    <% if !post.pet.photos.empty?  %>
                      <%= cl_image_tag post.pet.photos.first.key, height: 150, width: 200, crop: :fill %>
                    <% end %>
                    <div class="card-trip-infos">
                        <div>
                          <h5><%= link_to post.title,  post_path(post), class:"text-decoration-none" %></h5>
                          <p class="t-overflow pb-3"><%= post.description %></p>
                          <div class="d-flex justify-content-center">
                            <div class="row">
                              <% if policy(post).edit? %>
                                  <%= link_to edit_post_path(post), class: "notification-actions text-decoration-none pb-2", id: "publication" do %>
                                      <i class="fas fa-pencil-alt">Editar post</i>
                                  <% end %>
                                  <%= link_to edit_pet_path(post.pet), class: "notification-actions text-decoration-none pb-2", id: "publication" do %>
                                      <i class="fas fa-paw">Editar mascota</i>
                                  <% end %>
                                <% end %>
                              <% if policy(post).destroy? %>
                                <%= link_to post_path(post), class: "notification-actions text-decoration-none", method: :delete, data: { confirm: 'Estas seguro?' } do %>
                                    <i class="far fa-trash-alt">Borrar post</i>
                                <% end %>
                              <% end %>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
              <% end %>
        </div>
      </div>
    </div>
    <% else %>
      <%= render "jumbotron", info: {
        title: "Aun no tienes Publicaciones",
        btn: "Crear publicación",
        btn_path: new_pet_path,
      } %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container mt-5 col-8" data-controller="insert-map">
  <div class="row d-flex justify-content-center">
    <div class="col-10">
      <h2 class="mb-3 text-left">Crea tu Publicación</h2>
      <%= simple_form_for [@pet, @post] do |f| %>
        <div class="row">
          <div class="col-10">
            <%= f.input :title, placeholder: "Título", label: false %>
          </div>
        </div>
        <div class="row">
            <div class="col-10">
              <%= f.input :description, as: :text , placeholder: "Descripcion", label: false, hint: 'Mínimo 10 caracteres' %>
            </div>
          </div>
          <div class="row">
            <div class="col-10">
                <%= f.input :status, :prompt => 'Reportar como',  label: false, collection: ['Perdido', 'Encontrado'] %>
              </div>
          </div>
          <div class="row">
            <div class="col-10 d-flex">
                <!--<%= link_to "Previsualizar", locate_path(@post), class: "btn-gradient text-decoration-none", id: "preview",
                      data: { insert_map_target: 'preview', action: 'click->insert-map#showMap'} %>-->
              <div class="flex-grow-1">
                <%= f.input :address, placeholder: "Dirección", label: false, class: "", input_html: { data: { insert_map_target: 'inputAddress' } } %>
              </div>
              <div class="flex-shrink-1 mt-2 ml-2">
              <%= link_to locate_path(@post), class: "btn-gradient text-decoration-none align-self-end", id: "preview",
                      data: { insert_map_target: 'preview', action: 'click->insert-map#showMap'} do %>
                    <i class="fas fa-map-marked"></i>
                <% end %>
              </div>
            </div>
          </div>
          <p class="d-none">Coordenadas</p>
          <div class="col-10 pl-0 pr-0">
              <div id="map" data-insert-map-target="map" style="height: 300px; width: 100%" data-marker="" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
          </div>
          <div id="out" data-insert-map-target="out">
          <p></p>
          <div class="container text-center">
            <div class="row">
              <div class="col">
                <%= f.button :submit, "Publicar", class: "btn-gradient mb-5" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@post.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @post.description %>
<% content_for :meta_image, cl_image_path(@post.pet.photos.first.key) %>
<section class="post-show-page">

  <div class="container">
  <!-- titulo -->

  <!-- img -->
  <div class="row d-flex justify-content-center pt-3">
    <div class="col-8 post-show-container">
      <div class="d-flex justify-content-center flex-wrap pt-5">
        <div class="card-photo">
          <% if @post.pet.photos.length == 1 %>
            <%= cl_image_tag @post.pet.photos.first.key, class: "p-3", crop: :thumb, 'data-toggle': :modal, 'data-target': "#photo0" %>
        </div>
        <% elsif @post.pet.photos.length == 2 %>
          <div class="d-flex align-items-center px-2">
            <%= cl_image_tag @post.pet.photos.first.key, height: 400, width: 400, class: "p-3", crop: :thumb, 'data-toggle': :modal, 'data-target': "#photo0" %>
            <%= cl_image_tag @post.pet.photos.second.key, height: 400, width: 400, class: "p-3", crop: :thumb, 'data-toggle': :modal, 'data-target': "#photo1" %>
          </div>
        <% elsif @post.pet.photos.length == 3 %>
          <div class="d-flex align-items-center px-2">
              <%= cl_image_tag @post.pet.photos.first.key, height: 400, width: 400, class: "p-3", crop: :thumb, 'data-toggle': :modal, 'data-target': "#photo0" %>
              <%= cl_image_tag @post.pet.photos.second.key, height: 400, width: 400, class: "p-3", crop: :thumb, 'data-toggle': :modal, 'data-target': "#photo1" %>
              <%= cl_image_tag @post.pet.photos.third.key, height: 400, width: 400, class: "p-3", crop: :thumb, 'data-toggle': :modal, 'data-target': "#photo2" %>
          </div>
        <% else %>
          <div class="image-grid">
            <% @post.pet.photos.each_with_index do |photo,index| %>
              <% if index == 0 %>
                <%= cl_image_tag photo.key, height: 500, width: 500, class: "image-grid-col-2 image-grid-row-2", crop: :thumb, 'data-toggle': :modal, 'data-target': "#photo#{index}" %>
              <% else %>
                <%= cl_image_tag photo.key, height: 500, width: 500, crop: :thumb, 'data-toggle': :modal, 'data-target': "#photo#{index}" %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <!-- descripcion -->
  <div class="container pt-3 col-8">
    <div class="row d-flex justify-content-between">
        <div class="card-description">
            <div class="card-post-header">
              <h2 class="post-title"><%= @post.title.capitalize%></h2>
            </div>
            <div class="card-post-description">
              <p><%= @post.description.capitalize %></p>
              <p>Se perdió el <%= @post.created_at.strftime("%d/%b/%Y") %></p>
                <div class="">
                  <div>
                    <div>
                      <p>Publicado por <%= @post.user.name %></p>
                    </div>
                    <div>
                      <% if @post.user.avatar.attached? %>
                        <%= cl_image_tag @post.user.avatar.key, class: "avatar"%>
                      <% else %>
                        <%= image_tag "user.png", alt: "User", class: "avatar"%>
                      <% end %>
                    </div>
                  </div>
                </div>
              <br>
            </div>
          </div>
          <div class="col-8 pl-0">
            <h3 class="py-3">Identifica a <strong><%= @post.pet.name %></strong> con las siguientes características: </h3>
          </div>
          <div class="pl-0 container d-flex justify-content-center">
            <div class="post-grid">
              <div class="detail">
                  <p><strong>Raza:</strong></p>
                  <p><%= @post.pet.breed.capitalize %></p>
              </div>
              <div class="detail">
                  <p><strong>Tamaño:</strong></p>
                  <p><%= @post.pet.size.capitalize %></p>
              </div>
              <div class="detail">
                  <p><strong>Edad:</strong></p>
                  <p> <%= @post.pet.age %> año</p>
              </div>
              <div class="detail">
                  <p><strong>Sexo:</strong></p>
                  <p><%= @post.pet.gender.capitalize %></p>
              </div>
              <div class="detail">
                  <p><strong>Color:</strong></p>
                  <p><%= @post.pet.color.capitalize %></p>
              </div>
              <div class="detail">
                  <p><strong>Tipo:</strong></p>
                  <p><%= @post.pet.animal.capitalize %></p>
              </div>
            </div>
          </div>

      <div class="map-post-container">
        <div data-controller="show-map">
          <p class="pt-5"><i class="fas fa-map-marked-alt"></i> Dirección <%= @post.address%></p>
          <div id="map" data-show-map-target="map"
            data-marker="<%= @marker.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
  </div>

    <div class="container d-flex justify-content-center pt-3">
        <div class="row">
              <% if user_signed_in? %>
                <% if @post.user.id != current_user.id %>
                  <div class="col-6 align-items-end px-0 d-flex justify-content-between text-center px-2 py-3">
                    <h5>¿Lo has visto?</h5>
                  </div>
                  <div class="col-6 px-0  d-flex justify-content-between text-center px-2 py-3">
                    <%= link_to "Contactar", post_chatrooms_path(@post.id), class:"btn btn-light-gradient", method: "post" %>
                  </div>
                <% end %>
              <% end %>
        </div>
    </div>

 <!-- btn -->
</section>

<%#= render "contact_form", post: @post %>
<%#= render "message_form", post: @post %>
<%= render "photos_gallery", post: @post %>